name: DeityDungeon
main: com.imdeity.deity.dungeon.DeityDungeon
version: 17.02.19
language: english.yml
authors: [vanZeben]
description: Dungeon Plugin for ImDeity.com
website: http://www.ImDeity.com/
softdepend: [DeityAPI]

commands:
    DungeonAdmin:
        aliases: []